// Fetch
export const FETCH_CATEGORY_STARTED = 'CATEGORY/FETCH_STARTED';
export const FETCH_CATEGORY_SUCCESS = 'CATEGORY/FETCH_SUCCESS';
export const FETCH_CATAGORY_FAILURE = 'CATEGORY/FETCH_FAILURE';

