export const GET_INFO_STARTED = 'ORDER/GET_INFO_STARTED';
export const GET_INFO_SUCCESS = 'ORDER/GET_INFO_SUCCESS';
export const GET_INFO_FAILURE = 'ORDER/GET_INFO_FAILURE';

export const CHANGE_INFO_STARTED = 'ORDER/CHANGE_INFO_STARTED';
export const CHANGE_INFO_SUCCESS = 'ORDER/CHANGE_INFO_SUCCESS';
export const CHANGE_INFO_FAILURE = 'ORDER/CHANGE_INFO_FAILURE';

export const MAKE_ORDER_STARTED = 'ORDER/MAKE_ORDER_STARTED';
export const MAKE_ORDER_SUCCESS = 'ORDER/MAKE_ORDER_SUCCESS';
export const MAKR_ORDER_FAILURE = 'ORDER/MAKE_ORDER_FAILURE';