// Fetch
export const FETCH_PRODUCT_STARTED = 'PRODUCT/FETCH_STARTED';
export const FETCH_PRODUCT_SUCCESS = 'PRODUCT/FETCH_SUCCESS';
export const FETCH_PRODUCT_FAILURE = 'PRODUCT/FETCH_FAILURE';

export const SHOW_PPRODUCT_DETAIL = 'PRODUCT/SHOW_PRODUCT_DETAIL';
export const SHOW_PRODUCT_COMMENT = 'PRODUCT/SHOW_PRODUCT_COMMENT';


export const ADD_SHOPPING_CART = 'PRODUCT/ADD_SHOPPING_CART';
export const CHOOSE_SIZE = 'PRODUCT/CHOOSE_SIZE';
export const CHOOSE_COLOR = 'PRODCUT/CHOOSE_COLOR';
export const CHOOSE_NUMBER = 'PRODUCT/CHOOSE_NUMBER';

export const INCREASE_NUMBER = 'PRODUCT/INCREASE_NUMBER';
export const DECREASE_NUMBER = 'PRODUCT/DECREASE_NUMBER';

export const CHANGE_ICON = 'PRODUCT/CHANGE_ICON';

export const REMOVE_ALL = 'PRODUCT/REMOVE_ALL';