// 加载轮播图片
export const FETCH_SLIDER_STARTED = 'SLIDER/FETCH_STARTED';
export const FETCH_SLIDER_SUCCESS = 'SLIDER/FETCH_SUCCESS';
export const FETCH_SLIDER_FAILURE = 'SLIDER/FETCH_FAILURE';
// 滚动 加载 男装信息
export const FETCH_MAN_STARTED = 'MAN/FETCH_STARTED';
export const FETCH_MAN_SUCCESS = 'MAN/FETCH_SUCCESS';
export const FETCH_MAN_FAILURE = 'MAN/FETCH_FAILURE';
// 滚动 加载 女装信息
export const FETCH_WOMAN_STARTED = 'WOMAN/FETCH_STARTED';
export const FETCH_WOMAN_SUCCESS = 'WOMAN/FETCH_SUCCESS';
export const FETCH_WOMAN_FAILURE = 'WOMAN/FETCH_FAILURE';
// 滚动 加载 评论相关
export const FETCH_COMMENT_STARTED = 'COMMENT/FETCH_STARTED';
export const FETCH_COMMENT_SUCCESS = 'COMMENT/FETCH_SUCCESS';
export const FETCH_COMMENT_FAILURE = 'COMMENT/FETCH_FAILURE';

